name: code_base_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^4.0.5
  http_cache_hive_store: ^5.0.1
  hive_ce: ^2.15.1
  intl: ^0.20.2
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  flutter_localization: ^0.3.3
  google_fonts: ^6.3.2
  injectable: ^2.5.2
  get_it: ^8.3.0
  retrofit: ^4.9.0
  flutter_gen: ^5.12.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.2.2
  http: ^1.5.0
  flutter_riverpod: ^2.6.1
  video_player: ^2.9.1
  go_router: ^17.0.0
  gap: ^3.0.1
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  retrofit_generator: ^10.0.6

flutter:
  uses-material-design: true
  generate: true
  # Assets
  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/fonts/
    - assets/env/.env.development
    - assets/env/.env.staging
    - assets/env/.env.production

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

  fonts:
    enabled: true

  colors:
    enabled: false
